#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake -j processPoroPerm
wmake -j processPoroSurf
wmake -j processConcentration
wmake -j processMaxVelocity
wmake -j processPhaseConcentration
wmake -j processInterfaceTransfer
wmake -j processSaturation
wmake -j processMeshCellCenters
wmake -j processSolidArea
wmake -j processHeatTransfer
wmake -j processRelPerm
wmake -j processRelPermPF
wmake -j processSpeciesTransfer
wmake -j processFF
wmake -j processDispersion
wmake -j processStressStrain
# ----------------------------------------------------------------- end-of-file
