#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake -j interFoam
wmake -j interOSFoam
wmake -j diffInterFoam
# ----------------------------------------------------------------- end-of-file
