rm -rf [1-9]*
rm -f 0/U
rm -f 0/p
rm -f 0/phi
rm -rf 0/uniform
rm -rf processor*/[1-9]*
rm -rf processor*/0/U
rm -rf processor*/0/p
rm -rf processor*/0/phi
rm -rf processor*/0/uniform
rm -f *Flow.out
rm -f poroPerm.csv
rm -f system/SPDict
