#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake -j erodeFoam
wmake -j smoothSolidSurface 
wmake -j mapFields
# ----------------------------------------------------------------- end-of-file
