#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake -j scalarTransportDBSFoam
wmake -j dispersionFoam
wmake -j laplacianFoam
# ----------------------------------------------------------------- end-of-file
