#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake -j reactiveTransportFoam
wmake -j reactiveTransportALEFoam
wmake -j reactiveTransportDBSFoam
# ----------------------------------------------------------------- end-of-file
