#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake -j $makeType interfaceProperties
wmake -j $makeType twoPhaseProperties
wmake -j $makeType immiscibleIncompressibleTwoPhaseMixture
wmake -j $makeType twoPhasePhaseFieldMixture
wmake -j $makeType incompressible
wmake -j $makeType immiscibleIncompressibleTwoPhasePhaseFieldMixture


# ----------------------------------------------------------------- end-of-file
