#!/bin/bash
cd ${0%/*} || exit 1

thermophysicalModels/Allwclean
wclean libso fvMotionSolver
wclean libso finiteVolume
wclean libso meshTools
wclean libso OpenFOAM
transportModels/Allwclean
solidModels/Allwclean
