#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

thermophysicalModels/Allwmake
wmake -j libso fvMotionSolver
wmake -j libso finiteVolume
wmake -j libso meshTools
wmake -j libso OpenFOAM
transportModels/Allwmake
solidModels/Allwmake
# ----------------------------------------------------------------- end-of-file
