#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

thermophysicalModels/Allwmake
wmake libso fvMotionSolver
wmake libso finiteVolume
wmake libso meshTools
wmake libso OpenFOAM
transportModels/Allwmake
solidModels/Allwmake
# ----------------------------------------------------------------- end-of-file
